<a href="https://colab.research.google.com/github/22wh1a04c6/Data-Science-Task/blob/main/NUMPY_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# creating and reshaping arrays
#create arrays
import numpy as np
arr1=np.random.randint(0,50,10)
arr1
arr2=np.random.randint(5,20,9)
arr2=arr2.reshape(3,3)

In [ ]:
arr1.ndim

1

In [ ]:
arr.ndim

2

In [ ]:
arr1.reshape(2,5)


array([[10, 39, 19, 24,  4],
       [12, 43, 15, 29, 14]])

In [ ]:
arr1.reshape(-1)

array([10, 39, 19, 24,  4, 12, 43, 15, 29, 14])

In [ ]:
arr2[1,2]

np.int64(15)

In [ ]:
arr2[0:2,1:3]
arr1[0:4]
arr1[::-1]

array([14, 29, 15, 43, 12,  4, 24, 19, 39, 10])

In [ ]:
#array arithematic
arr3=np.arange(1,11)
print(arr3)
print(arr1+arr3)
print(arr1*arr3)
print(arr3-5)

[ 1  2  3  4  5  6  7  8  9 10]
[11 41 22 28  9 18 50 23 38 24]
[ 10  78  57  96  20  72 301 120 261 140]
[-4 -3 -2 -1  0  1  2  3  4  5]


In [ ]:
arr4=np.random.rand(5)
print(arr4)
arr5=np.random.randn(5)
print(arr5)

[0.84172178 0.89707583 0.94315022 0.25919552 0.30600844]
[-0.47117809  0.34236388  1.88670387 -1.96170009 -1.65401159]


In [ ]:
# write a program that asks user to input a number n and then generates a n into n array of random integers between 1 and 100
n=int(input())
arr1=np.random.randint(1,100,n)
print(arr1)
#find sum of all the elements in the array
np.sum(arr1)

3
[32 31 46]


np.int64(109)